package veterinary.management;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author Administrator
 */
public class ClientForm extends javax.swing.JFrame {

    EklemeIslemeleri eislem = new EklemeIslemeleri();
    GuncellemeIslemleri gi = new GuncellemeIslemleri();
    Database db = new Database();
    SilmeIslemleri si = new SilmeIslemleri();

    /**
     * Creates new form ClientForm
     */
    public ClientForm() {
        initComponents();
        setTitle("Clients");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        updateBut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        deleteBut = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        clName = new javax.swing.JTextField();
        clAddress = new javax.swing.JTextField();
        clSSN = new javax.swing.JTextField();
        insertBut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        getTable = new javax.swing.JButton();
        menuButton = new javax.swing.JButton();
        phoneNoBut = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        searchBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("clientName");

        updateBut.setText("UPDATE");
        updateBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButActionPerformed(evt);
            }
        });

        jLabel2.setText("clientAddress");

        deleteBut.setText("DELETE");
        deleteBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButActionPerformed(evt);
            }
        });

        jLabel3.setText("clientSSN:");

        insertBut.setText("INSERT");
        insertBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Client Name", "Client Address", "Client SSN"
                }));
        jScrollPane1.setViewportView(jTable1);

        getTable.setText("Get Table");
        getTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getTableActionPerformed(evt);
            }
        });

        menuButton.setText("Menu");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        phoneNoBut.setText("Phone No");
        phoneNoBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNoButActionPerformed(evt);
            }
        });

        searchBut.setText("Search");
        searchBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(14, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel1)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(jLabel3))
                                                                .addGap(33, 33, 33)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(clName,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                125,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(clSSN,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                125,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(clAddress,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        125,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(26, 26, 26)
                                                                                .addComponent(insertBut,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        89,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(42, 42, 42)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(updateBut,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                89, Short.MAX_VALUE)
                                                                        .addComponent(phoneNoBut,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(getTable)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(searchField,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 130,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(searchBut)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addComponent(menuButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(deleteBut, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                89, Short.MAX_VALUE))
                                                .addGap(23, 23, 23)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(clName, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(clAddress, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(insertBut, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(updateBut, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(deleteBut, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(clSSN, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(31, 31, 31)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(getTable)
                                                                        .addComponent(searchField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                25,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(searchBut)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(menuButton,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE))))
                                        .addComponent(phoneNoBut, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(14, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertButActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_insertButActionPerformed

        eislem.clientekle(clName.getText(), clAddress.getText(), clSSN.getText());
        JOptionPane.showMessageDialog(this, "The operation completed successfully");

    }// GEN-LAST:event_insertButActionPerformed

    int temp = 1;
    String oldSSN = "";

    private void updateButActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_updateButActionPerformed
        temp++;
        String newName = null;
        String newAddress = null;
        String newSSN = null;

        if (temp == 2) {

            oldSSN = clSSN.getText();
            JOptionPane.showMessageDialog(this, "Enter new values");

        }

        else if (temp == 3) {

            newName = clName.getText();
            newAddress = clAddress.getText();
            newSSN = clSSN.getText();

            gi.clientGuncelle(oldSSN, newName, newAddress, newSSN);
            JOptionPane.showMessageDialog(this, "The operation completed successfully");

        } else if (temp > 3) {

            clName.setText("");
            clAddress.setText("");
            clSSN.setText("");
            oldSSN = "";
            newName = "";
            newAddress = "";
            newSSN = "";
            temp = 1;
        }

    }// GEN-LAST:event_updateButActionPerformed

    private void getTableActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_getTableActionPerformed
        TableAdder tableAdder = new TableAdder();
        tableAdder.clientTable(jTable1);
    }// GEN-LAST:event_getTableActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_menuButtonActionPerformed
        MainPage mp = new MainPage();
        setVisible(false);
        mp.setVisible(true);
    }// GEN-LAST:event_menuButtonActionPerformed

    private void deleteButActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteButActionPerformed
        String curSSN = clSSN.getText();
        si.clientDelete(curSSN);
        JOptionPane.showMessageDialog(this, "The operation completed successfully");
    }// GEN-LAST:event_deleteButActionPerformed

    private void phoneNoButActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_phoneNoButActionPerformed
        clientNoForm cnf = new clientNoForm();
        cnf.setVisible(true);
    }// GEN-LAST:event_phoneNoButActionPerformed

    private void searchButActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_searchButActionPerformed
        TableAdder ta = new TableAdder();
        ta.search(jTable1, searchField.getText());
    }// GEN-LAST:event_searchButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField clAddress;
    private javax.swing.JTextField clName;
    private javax.swing.JTextField clSSN;
    private javax.swing.JButton deleteBut;
    private javax.swing.JButton getTable;
    private javax.swing.JButton insertBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton menuButton;
    private javax.swing.JButton phoneNoBut;
    private javax.swing.JButton searchBut;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton updateBut;
    // End of variables declaration//GEN-END:variables
}
