/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veterinary.management;

public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_client = new javax.swing.JButton();
        btn_pet = new javax.swing.JButton();
        btn_employee = new javax.swing.JButton();
        btn_reservation = new javax.swing.JButton();
        btn_product = new javax.swing.JButton();
        purchaseBut = new javax.swing.JButton();
        queriesBut = new javax.swing.JButton();
        treatmentsBut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Veterinary Management");

        btn_client.setText("Client");
        btn_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientActionPerformed(evt);
            }
        });

        btn_pet.setText("Pet");
        btn_pet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_petActionPerformed(evt);
            }
        });

        btn_employee.setText("Employee");
        btn_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_employeeActionPerformed(evt);
            }
        });

        btn_reservation.setText("Reservation");
        btn_reservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reservationActionPerformed(evt);
            }
        });

        btn_product.setText("Product");
        btn_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_productActionPerformed(evt);
            }
        });

        purchaseBut.setText("Purchases");
        purchaseBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseButActionPerformed(evt);
            }
        });

        queriesBut.setText("Queries");
        queriesBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queriesButActionPerformed(evt);
            }
        });

        treatmentsBut.setText("Treatments");
        treatmentsBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treatmentsButActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Veterinary Management System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(63, 63, 63)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(130, 130, 130)
                                                                .addComponent(queriesBut,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 266,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                        .addComponent(btn_client,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(btn_pet,
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                164,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(purchaseBut,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(btn_employee,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(btn_product,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                162,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(btn_reservation,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(treatmentsBut,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                165,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(55, 55, 55)
                                                .addComponent(jLabel1)))
                                .addContainerGap(80, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn_client)
                                        .addComponent(btn_employee)
                                        .addComponent(btn_reservation))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn_pet)
                                        .addComponent(btn_product)
                                        .addComponent(treatmentsBut))
                                .addGap(32, 32, 32)
                                .addComponent(purchaseBut)
                                .addGap(68, 68, 68)
                                .addComponent(queriesBut)
                                .addGap(24, 24, 24)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clientActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_clientActionPerformed

        ClientForm clfrm = new ClientForm();
        setVisible(false);
        clfrm.setLocationRelativeTo(null);
        clfrm.setVisible(true);

    }// GEN-LAST:event_btn_clientActionPerformed

    private void btn_employeeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_employeeActionPerformed
        EmployeeForm ef = new EmployeeForm();
        setVisible(false);
        ef.setLocationRelativeTo(null);
        ef.setVisible(true);
    }// GEN-LAST:event_btn_employeeActionPerformed

    private void btn_reservationActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_reservationActionPerformed

        ReservationForm rf = new ReservationForm();
        setVisible(false);
        rf.setLocationRelativeTo(null);
        rf.setVisible(true);
    }// GEN-LAST:event_btn_reservationActionPerformed

    private void btn_petActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_petActionPerformed
        PetForm pf = new PetForm();
        setVisible(false);
        pf.setLocationRelativeTo(null);
        pf.setVisible(true);
    }// GEN-LAST:event_btn_petActionPerformed

    private void btn_productActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_productActionPerformed
        ProductForm pf = new ProductForm();
        setVisible(false);
        pf.setLocationRelativeTo(null);
        pf.setVisible(true);

    }// GEN-LAST:event_btn_productActionPerformed

    private void purchaseButActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_purchaseButActionPerformed
        PurchasesForm pf = new PurchasesForm();
        setVisible(false);
        pf.setLocationRelativeTo(null);
        pf.setVisible(true);
    }// GEN-LAST:event_purchaseButActionPerformed

    private void queriesButActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_queriesButActionPerformed
        QueriesForm qf = new QueriesForm();
        setVisible(false);
        qf.setLocationRelativeTo(null);
        qf.setVisible(true);
    }// GEN-LAST:event_queriesButActionPerformed

    private void treatmentsButActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_treatmentsButActionPerformed
        treatmentForm tb = new treatmentForm();
        setVisible(false);
        tb.setLocationRelativeTo(null);
        tb.setVisible(true);

    }// GEN-LAST:event_treatmentsButActionPerformed

    public void clientlistele() {

    }

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Database database = new Database();
                new MainPage().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_client;
    private javax.swing.JButton btn_employee;
    private javax.swing.JButton btn_pet;
    private javax.swing.JButton btn_product;
    private javax.swing.JButton btn_reservation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton purchaseBut;
    private javax.swing.JButton queriesBut;
    private javax.swing.JButton treatmentsBut;
    // End of variables declaration//GEN-END:variables
}
