package veterinary.management;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author tolga
 */
public class QueriesForm extends javax.swing.JFrame {

    Queries qr = new Queries();

    /**
     * Creates new form QueriesForm
     */
    public QueriesForm() {
        initComponents();
        setTitle("Queries");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mostTreat = new javax.swing.JButton();
        mostSoldMedicineBut = new javax.swing.JButton();
        mostCummonRaceBut = new javax.swing.JButton();
        mostComVetBut = new javax.swing.JButton();
        avgProductPriceBut = new javax.swing.JButton();
        manuBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mostTreat.setText("Most Used Treat");
        mostTreat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostTreatActionPerformed(evt);
            }
        });

        mostSoldMedicineBut.setText("Most Sold Medicine");
        mostSoldMedicineBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostSoldMedicineButActionPerformed(evt);
            }
        });

        mostCummonRaceBut.setText("Most Common Race");
        mostCummonRaceBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostCummonRaceButActionPerformed(evt);
            }
        });

        mostComVetBut.setText("Most Operating Vet");
        mostComVetBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostComVetButActionPerformed(evt);
            }
        });

        avgProductPriceBut.setText("Average of Product Prices");
        avgProductPriceBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgProductPriceButActionPerformed(evt);
            }
        });

        manuBut.setText("Menu");
        manuBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(mostCummonRaceBut, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mostTreat, javax.swing.GroupLayout.DEFAULT_SIZE, 206,
                                                Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79,
                                        Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(mostSoldMedicineBut, javax.swing.GroupLayout.DEFAULT_SIZE, 223,
                                                Short.MAX_VALUE)
                                        .addComponent(mostComVetBut, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(73, 73, 73))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(174, 174, 174)
                                                .addComponent(avgProductPriceBut,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 223,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(manuBut, javax.swing.GroupLayout.PREFERRED_SIZE, 134,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mostTreat)
                                        .addComponent(mostSoldMedicineBut))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mostCummonRaceBut)
                                        .addComponent(mostComVetBut))
                                .addGap(32, 32, 32)
                                .addComponent(avgProductPriceBut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307,
                                        Short.MAX_VALUE)
                                .addComponent(manuBut, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostTreatActionPerformed(ActionEvent evt) {// GEN-FIRST:event_mostTreatActionPerformed
        String message = qr.mostUsedTreat();
        JOptionPane.showMessageDialog(this, message.toString());

    }// GEN-LAST:event_mostTreatActionPerformed

    private void mostSoldMedicineButActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mostSoldMedicineButActionPerformed
        String message = qr.mostSoldMedicine();
        JOptionPane.showMessageDialog(this, message.toString());
    }// GEN-LAST:event_mostSoldMedicineButActionPerformed

    private void mostCummonRaceButActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mostCummonRaceButActionPerformed
        String message = qr.mostCommonRace();
        JOptionPane.showMessageDialog(this, message.toString());
    }// GEN-LAST:event_mostCummonRaceButActionPerformed

    private void mostComVetButActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mostComVetButActionPerformed
        String message = qr.mostOperatingVet();
        JOptionPane.showMessageDialog(this, message.toString());
    }// GEN-LAST:event_mostComVetButActionPerformed

    private void avgProductPriceButActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_avgProductPriceButActionPerformed
        String message = qr.avgProductPrice();
        JOptionPane.showMessageDialog(this, message.toString());
    }// GEN-LAST:event_avgProductPriceButActionPerformed

    private void manuButActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_manuButActionPerformed
        MainPage mp = new MainPage();
        setVisible(false);
        mp.setVisible(true);
    }// GEN-LAST:event_manuButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QueriesForm.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QueriesForm.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QueriesForm.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QueriesForm.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QueriesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avgProductPriceBut;
    private javax.swing.JButton manuBut;
    private javax.swing.JButton mostComVetBut;
    private javax.swing.JButton mostCummonRaceBut;
    private javax.swing.JButton mostSoldMedicineBut;
    private javax.swing.JButton mostTreat;
    // End of variables declaration//GEN-END:variables
}
