package veterinary.management;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class treatmentForm extends javax.swing.JFrame {

    EklemeIslemeleri eislem = new EklemeIslemeleri();
    GuncellemeIslemleri gi = new GuncellemeIslemleri();
    SilmeIslemleri si = new SilmeIslemleri();

    public treatmentForm() {
        initComponents();
        ssnComboBox();
        petIdComboBox();
        treatComboBox();
        setTitle("Treatments");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        petIdCombo = new javax.swing.JComboBox<>();
        vetSsnCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        insertBut = new javax.swing.JButton();
        updateBut = new javax.swing.JButton();
        deleteBut = new javax.swing.JButton();
        tableBut = new javax.swing.JButton();
        menuBut = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        treatCombo = new javax.swing.JComboBox<>();
        showPetIdBut = new javax.swing.JButton();
        showVetsBut = new javax.swing.JButton();
        treatsBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pet ID:");

        jLabel2.setText("Vet's SSN:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Pet ID", "Vet SSN", "Treat ID"
                }));
        jScrollPane1.setViewportView(jTable1);

        insertBut.setText("INSERT");
        insertBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButActionPerformed(evt);
            }
        });

        updateBut.setText("UPDATE");
        updateBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButActionPerformed(evt);
            }
        });

        deleteBut.setText("DELETE");
        deleteBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButActionPerformed(evt);
            }
        });

        tableBut.setText("Get Table");
        tableBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableButActionPerformed(evt);
            }
        });

        menuBut.setText("Menu");
        menuBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButActionPerformed(evt);
            }
        });

        jLabel3.setText("treat ID:");

        treatCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treatComboActionPerformed(evt);
            }
        });

        showPetIdBut.setText("Show Pet IDs");
        showPetIdBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPetIdButActionPerformed(evt);
            }
        });

        showVetsBut.setText("Show Vets");
        showVetsBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showVetsButActionPerformed(evt);
            }
        });

        treatsBut.setText("Treats");
        treatsBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treatsButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel1)
                                                                        .addComponent(jLabel2))
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(27, 27, 27)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(vetSsnCombo, 0, 149, Short.MAX_VALUE)
                                                        .addComponent(petIdCombo, 0,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(treatCombo, 0,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(68, 68, 68)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(insertBut, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(showPetIdBut,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(updateBut, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                89, Short.MAX_VALUE)
                                                        .addComponent(treatsBut, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(deleteBut,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 97,
                                                                        Short.MAX_VALUE)
                                                                .addGap(12, 12, 12))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(showVetsBut,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addContainerGap())))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane1)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addComponent(tableBut,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 98,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(menuBut,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 92,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addContainerGap()))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(petIdCombo,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(vetSsnCombo,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(46, 46, 46)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(insertBut, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(updateBut, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(deleteBut, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(treatCombo,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(showVetsBut, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(treatsBut)
                                                        .addComponent(showPetIdBut))
                                                .addGap(20, 20, 20)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tableBut, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(menuBut, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ssnComboBox() {

        String query = "SELECT vetSSN FROM vet ORDER BY vetSSN";
        Database db = new Database();
        try {
            PreparedStatement pst = db.getCon().prepareStatement(query);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {

                String ssn = rs.getString("vetSSN");

                vetSsnCombo.addItem(ssn);

            }

        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }

    }

    private void petIdComboBox() {

        String query = "SELECT petID FROM pet ORDER BY petID";
        Database db = new Database();
        try {
            PreparedStatement pst = db.getCon().prepareStatement(query);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {

                String id = rs.getString("petID");

                petIdCombo.addItem(id);

            }

        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }

    }

    private void treatComboBox() {

        treatCombo.removeAllItems();

        String query = "SELECT treatID FROM treatment ORDER BY treatID";
        Database db = new Database();
        try {
            PreparedStatement pst = db.getCon().prepareStatement(query);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {

                String id = rs.getString("treatID");

                treatCombo.addItem(id);

            }

        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }

    }

    private void insertButActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_insertButActionPerformed
        eislem.treatmentekle(String.valueOf(petIdCombo.getSelectedItem()),
                String.valueOf(vetSsnCombo.getSelectedItem()));
        treatComboBox();
    }// GEN-LAST:event_insertButActionPerformed

    int temp = 1;
    String treatID = "";

    private void updateButActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_updateButActionPerformed
        temp++;
        String newPetID = null;
        String newSSN = null;

        if (temp == 2) {

            treatID = String.valueOf(treatCombo.getSelectedItem());

        }

        else if (temp == 3) {

            newPetID = String.valueOf(petIdCombo.getSelectedItem());
            newSSN = String.valueOf(vetSsnCombo.getSelectedItem());

            gi.treatmentGuncelle(newPetID, newSSN, treatID);
            treatComboBox();

        } else if (temp > 3) {

            newSSN = null;
            newPetID = null;
            treatID = null;
            temp = 1;
        }
    }// GEN-LAST:event_updateButActionPerformed

    private void deleteButActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteButActionPerformed
        si.treatmentDelete(String.valueOf(treatCombo.getSelectedItem()));
        treatComboBox();
    }// GEN-LAST:event_deleteButActionPerformed

    private void menuButActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_menuButActionPerformed
        MainPage mp = new MainPage();
        setVisible(false);
        mp.setVisible(true);
    }// GEN-LAST:event_menuButActionPerformed

    private void tableButActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tableButActionPerformed
        TableAdder ta = new TableAdder();
        ta.treatmentTable(jTable1);
    }// GEN-LAST:event_tableButActionPerformed

    private void treatComboActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_treatComboActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_treatComboActionPerformed

    private void showPetIdButActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_showPetIdButActionPerformed
        PetForm pf = new PetForm();
        pf.setVisible(true);
        pf.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }// GEN-LAST:event_showPetIdButActionPerformed

    private void showVetsButActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_showVetsButActionPerformed
        EmployeeForm ef = new EmployeeForm();
        ef.setVisible(true);
        ef.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }// GEN-LAST:event_showVetsButActionPerformed

    private void treatsButActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_treatsButActionPerformed
        TreatsForm tf = new TreatsForm();
        tf.setVisible(true);
        tf.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }// GEN-LAST:event_treatsButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(treatmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(treatmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(treatmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(treatmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new treatmentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBut;
    private javax.swing.JButton insertBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton menuBut;
    private javax.swing.JComboBox<String> petIdCombo;
    private javax.swing.JButton showPetIdBut;
    private javax.swing.JButton showVetsBut;
    private javax.swing.JButton tableBut;
    private javax.swing.JComboBox<String> treatCombo;
    private javax.swing.JButton treatsBut;
    private javax.swing.JButton updateBut;
    private javax.swing.JComboBox<String> vetSsnCombo;
    // End of variables declaration//GEN-END:variables
}
